# Generated by Django 4.2.5 on 2023-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("year", models.IntegerField()),
            ],
        ),
    ]
