# Generated by Django 4.2.5 on 2023-10-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="name",
            new_name="owner_name",
        ),
    ]
