# Generated by Django 4.2.5 on 2023-10-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_name_car_owner_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="model",
            new_name="car_model",
        ),
    ]
